# Generated by Django 5.1.4 on 2025-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdkdemoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=256)),
                ('log_id', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('timezone_offset', models.IntegerField(blank=True, null=True)),
                ('attend_status', models.CharField(blank=True, max_length=256, null=True)),
                ('action', models.CharField(blank=True, max_length=256, null=True)),
                ('job_code', models.IntegerField(blank=True, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('body_temperature', models.IntegerField(blank=True, null=True)),
                ('attend_only', models.BooleanField()),
                ('expired', models.BooleanField()),
                ('latitude', models.CharField(blank=True, max_length=256, null=True)),
                ('longitude', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device_id', 'log_id'), name='device_log_id', nulls_distinct=False)],
            },
        ),
    ]
