# Generated by Django 5.1.4 on 2025-01-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdkdemoapp', '0002_attendancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=256)),
                ('log_id', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=256, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
