# Generated by Django 4.2.29 on 2026-04-22 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sdkdemoapp', '0004_oemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=256)),
                ('event', models.CharField(choices=[('connect', 'Connected'), ('disconnect', 'Disconnected')], max_length=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('department', models.IntegerField(default=0)),
                ('privilege', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('card', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('timeset_1', models.IntegerField(default=-1)),
                ('timeset_2', models.IntegerField(default=-1)),
                ('timeset_3', models.IntegerField(default=-1)),
                ('timeset_4', models.IntegerField(default=-1)),
                ('timeset_5', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterlockState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('punched_device', models.CharField(max_length=256)),
                ('punch_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('interlock_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-punch_time'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=256, unique=True)),
                ('friendly_name', models.CharField(blank=True, default='', max_length=256)),
                ('location', models.CharField(blank=True, default='', max_length=256)),
                ('terminal_type', models.CharField(blank=True, default='', max_length=128)),
                ('product_name', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('interlock_enabled', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=64)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sdkdemoapp.zone')),
            ],
        ),
    ]
