# Generated by Django 4.2.29 on 2026-04-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdkdemoapp', '0005_new_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oemsettings',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='oemsettings',
            name='logo',
            field=models.FileField(blank=True, upload_to='oem/'),
        ),
    ]
